name: Crawl and Push Reviews

on:
  schedule:
    - cron: '0 0 * * 0' # 매주 일요일 0시
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write # GitHub Actions가 저장소에 푸시할 수 있도록 쓰기 권한 추가
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Naver Blog Crawler
        run: python3 crawler/naver_blog.py
      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add data/reviews/
          git commit -m 'auto: update reviews' || echo 'No changes to commit'
          git push 
